name: ci

on:
  push:
    paths-ignore:
      - 'playground/**'
      - 'docs/**'
      - '**/*.md'
      - 'README.md'
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-redis@v1
        name: Start and ping redis server
        with:
          redis-version: "6.x"
      - run: redis-cli ping

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install && pnpm dev:prepare

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm prepack
